apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "apps"
spec:
  backend:
    serviceName: rainfall-service
    servicePort: 5000

