apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "koverholt-apps-ip"
spec:
  rules:
  - host: rainfall.koverholt.com
    http:
      paths:
        - backend:
            serviceName: rainfall-service
            servicePort: 5000
